<a href="https://colab.research.google.com/github/tommystarrrrrrr/2025_Kecerdasan-Buatan/blob/main/Data_Pre_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# JOBSHEET 07

### 1. Data Preparation dengan One Hot Encoding

In [15]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

gender = ['perempuan', 'laki-laki', 'laki-laki', 'perempuan', 'perempuan']

df = pd.DataFrame({'gender': gender})

encoder = OneHotEncoder()

encoded_df = pd.DataFrame(
    encoder.fit_transform(df[['gender']]).toarray(),
    columns=encoder.get_feature_names_out(['gender'])
)

df_encoded = pd.concat([df, encoded_df], axis=1)

df_encoded

      gender  gender_laki-laki  gender_perempuan
0  perempuan               0.0               1.0
1  laki-laki               1.0               0.0
2  laki-laki               1.0               0.0
3  perempuan               0.0               1.0
4  perempuan               0.0               1.0

### 2. Data Preparation dengan Outlier Removal

In [2]:
import pandas as pd
import numpy as np

# membuat data frame contoh
df = pd.DataFrame({
    'A': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'B': [15, 20, 25, 30, 35, 40, 45, 50, 55, 500]
})

# mencari nilai z-score untuk setiap data point pada kolom B
z_scores = np.abs((df['B'] - df['B'].mean()) / df['B'].std())

# menghilangkan data point yang memiliki z-score lebih besar dari 3
df_clean = df.loc[round(z_scores) < 3]

# menampilkan data frame yang telah di-clean
print(df_clean)

   A   B
0  1  15
1  2  20
2  3  25
3  4  30
4  5  35
5  6  40
6  7  45
7  8  50
8  9  55

### 3. Data Preparation dengan Normalization

In [4]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
# membuat data frame contoh
df = pd.DataFrame({
    'Nama': ['Andi', 'Budi', 'Cindy', 'Diana', 'Eka', 'lala'],
    'Gaji': [3000000, 5000000, 7000000, 9000000, 11000000, 9000000],
    'Umur': [25, 30, 35, 40, 45, 30]
})
# normalisasi data gaji dan umur menggunakan MinMaxScaler
scaler = MinMaxScaler()
df[['Gaji', 'Umur']] = scaler.fit_transform(df[['Gaji', 'Umur']])

# menampilkan data frame hasil normalisasi
df

    Nama  Gaji  Umur
0   Andi  0.00  0.00
1   Budi  0.25  0.25
2  Cindy  0.50  0.50
3  Diana  0.75  0.75
4    Eka  1.00  1.00
5   lala  0.75  0.25

### 4. Data Preparation dengan Standarization

In [20]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

# membuat data frame contoh
df = pd.DataFrame({
    'Nama': ['Andi', 'Budi', 'Cindy', 'Diana', 'Eka', 'lala'],
    'Gaji': [3000000, 5000000, 7000000, 9000000, 11000000, 9000000],
    'Umur': [25, 30, 35, 40, 45, 30]
})

# normalisasi data gaji dan umur menggunakan MinMaxScaler
scaler = StandardScaler()
df[['Gaji', 'Umur']] = scaler.fit_transform(df[['Gaji', 'Umur']])

# menampilkan data frame hasil normalisasi
df

    Nama      Gaji      Umur
0   Andi -1.612452 -1.364382
1   Budi -0.868243 -0.620174
2  Cindy -0.124035  0.124035
3  Diana  0.620174  0.868243
4    Eka  1.364382  1.612452
5   lala  0.620174 -0.620174

### 5. Pembuatan DataSet

In [21]:
from sklearn.model_selection import train_test_split
import pandas as pd

# membuat data frame contoh
df = pd.DataFrame({
    'X': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Y': [15, 20, 25, 30, 35, 40, 45, 50, 55, 60]
})


# membagi data menjadi data latih dan data uji dengan rasio 80:20
X_train, X_test, y_train, y_test = train_test_split(df[['X']], df[['Y']], test_size=0.2, random_state=42)
# menampilkan data latih
print('Data Latih')
print('X_train:', X_train)
print('y_train:', y_train)

# menampilkan data uji
print('\nData Uji')
print('X_test:', X_test)
print('y_test:', y_test)

Data Latih
X_train:     X
5   6
0   1
7   8
2   3
9  10
4   5
3   4
6   7
y_train:     Y
5  40
0  15
7  50
2  25
9  60
4  35
3  30
6  45

Data Uji
X_test:    X
8  9
1  2
y_test:     Y
8  55
1  20

### Implementasi Pembagian data pada data heart.csv

In [17]:
from sklearn.model_selection import train_test_split
import pandas as pd

# Import data heart.csv
df = pd.read_csv('heart.csv');
df

# ambil 13 data dan masukan kedalam variabel data
data = df.iloc[:, :13]
data

# Rubah data ke array
data = data.values
data

# Masukan data pada kolom terakhir dan masukan kedalam variabel label
label = df.iloc[:, -1]

# Rubah data ke array
label = label.values
label

# Bagi data menjadi data training dan data testing
data_train, data_test, label_train, label_test = train_test_split(data, label, test_size=0.2, random_state=42)

print('Ukuran data latih:', data_train.shape)
print('Ukuran data uji:', data_test.shape)

Ukuran data latih: (734, 12)
Ukuran data uji: (184, 12)

### Cross Validation

In [37]:
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris

iris = load_iris()
data = iris.data
label = iris.target

dt = DecisionTreeClassifier()

from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris

iris = load_iris()
data = iris.data
label = iris.target

dt = DecisionTreeClassifier()

scores = cross_val_score(dt, data, label, cv=5)

print('Hasil cross validation:', scores)

Hasil cross validation: [0.96666667 0.96666667 0.9        1.         1.        ]

# TUGAS PRAKTIKUM

### 1. Data Preparation dengan One Hot Encoding

In [38]:
# 1. Import library yang diperlukan
import pandas as pd

# 2. Load dataset
df = pd.read_csv("SupplyChainGHGEmissionFactors.csv")

# 3. Tampilkan data awal
print("Data Awal:")
display(df.head())

# 4. Terapkan One Hot Encoding untuk kolom kategorikal
df_encoded = pd.get_dummies(df, columns=['2017 NAICS Title', 'GHG', 'Unit', 'Reference USEEIO Code'])

# 5. Tampilkan hasil setelah One Hot Encoding
print("Data Setelah One Hot Encoding:")
display(df_encoded.head())

# 6. Tampilkan informasi dimensi data sebelum dan sesudah encoding
print("Jumlah Baris dan Kolom:")
summary = pd.DataFrame({
    "Tahapan": ["Sebelum One Hot Encoding", "Setelah One Hot Encoding"],
    "Jumlah Baris": [df.shape[0], df_encoded.shape[0]],
    "Jumlah Kolom": [df.shape[1], df_encoded.shape[1]]
})
display(summary)

Data Awal:

,2017 NAICS Code,2017 NAICS Title,GHG,Unit,Supply Chain Emission Factors without Margins,Margins of Supply Chain Emission Factors,Supply Chain Emission Factors with Margins,Reference USEEIO Code
0,111110,Soybean Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.488,0.044,0.532,1111A0
1,111120,Oilseed (except Soybean) Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.488,0.044,0.532,1111A0
2,111130,Dry Pea and Bean Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.809,0.040,0.848,1111B0
3,111140,Wheat Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.809,0.040,0.848,1111B0
4,111150,Corn Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.809,0.040,0.848,1111B0

Data Setelah One Hot Encoding:

,2017 NAICS Code,Supply Chain Emission Factors without Margins,Margins of Supply Chain Emission Factors,Supply Chain Emission Factors with Margins,2017 NAICS Title_Abrasive Product Manufacturing,2017 NAICS Title_Adhesive Manufacturing,2017 NAICS Title_Administrative Management and General Management Consulting Services,2017 NAICS Title_Advertising Agencies,2017 NAICS Title_Advertising Material Distribution Services,"2017 NAICS Title_Agents and Managers for Artists, Athletes, Entertainers, and Other Public Figures",...,Reference USEEIO Code_811200,Reference USEEIO Code_811300,Reference USEEIO Code_811400,Reference USEEIO Code_812100,Reference USEEIO Code_812200,Reference USEEIO Code_812300,Reference USEEIO Code_812900,Reference USEEIO Code_813100,Reference USEEIO Code_813A00,Reference USEEIO Code_813B00
0,111110,0.488,0.044,0.532,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,111120,0.488,0.044,0.532,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,111130,0.809,0.040,0.848,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,111140,0.809,0.040,0.848,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,111150,0.809,0.040,0.848,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

Jumlah Baris dan Kolom:

                    Tahapan  Jumlah Baris  Jumlah Kolom
0  Sebelum One Hot Encoding          1016             8
1  Setelah One Hot Encoding          1016          1408

### 2. Data Preparation dengan Outlier Removal

In [39]:
# 1. Import library yang diperlukan
import pandas as pd

# 2. Load dataset
df = pd.read_csv("SupplyChainGHGEmissionFactors.csv")

# 3. Tampilkan data awal
print("Data Awal:")
display(df.head())

# 4. Definisikan kolom numerik yang akan diperiksa outlier-nya
num_cols = [
    'Supply Chain Emission Factors without Margins',
    'Margins of Supply Chain Emission Factors',
    'Supply Chain Emission Factors with Margins'
]

# 5. Fungsi untuk menghapus outlier berdasarkan IQR
def remove_outliers_iqr(data, columns):
    Q1 = data[columns].quantile(0.25)
    Q3 = data[columns].quantile(0.75)
    IQR = Q3 - Q1
    condition = ~((data[columns] < (Q1 - 1.5 * IQR)) | (data[columns] > (Q3 + 1.5 * IQR))).any(axis=1)
    return data[condition]

# 6. Hapus outlier dari data
df_cleaned = remove_outliers_iqr(df, num_cols)

# 7. Tampilkan hasil setelah menghapus outlier
print("Data Setelah Outlier Removal:")
display(df_cleaned.head())

# 8. Tampilkan jumlah baris sebelum dan sesudah
summary = pd.DataFrame({
    "Tahapan": ["Sebelum Outlier Removal", "Setelah Outlier Removal"],
    "Jumlah Baris": [df.shape[0], df_cleaned.shape[0]],
    "Jumlah Kolom": [df.shape[1], df_cleaned.shape[1]]
})
print("Ringkasan Jumlah Data:")
display(summary)

Data Awal:

,2017 NAICS Code,2017 NAICS Title,GHG,Unit,Supply Chain Emission Factors without Margins,Margins of Supply Chain Emission Factors,Supply Chain Emission Factors with Margins,Reference USEEIO Code
0,111110,Soybean Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.488,0.044,0.532,1111A0
1,111120,Oilseed (except Soybean) Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.488,0.044,0.532,1111A0
2,111130,Dry Pea and Bean Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.809,0.040,0.848,1111B0
3,111140,Wheat Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.809,0.040,0.848,1111B0
4,111150,Corn Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.809,0.040,0.848,1111B0

Data Setelah Outlier Removal:

,2017 NAICS Code,2017 NAICS Title,GHG,Unit,Supply Chain Emission Factors without Margins,Margins of Supply Chain Emission Factors,Supply Chain Emission Factors with Margins,Reference USEEIO Code
0,111110,Soybean Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.488,0.044,0.532,1111A0
1,111120,Oilseed (except Soybean) Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.488,0.044,0.532,1111A0
8,111211,Potato Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.591,0.041,0.631,111200
9,111219,Other Vegetable (except Potato) and Melon Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.591,0.041,0.631,111200
10,111310,Orange Groves,All GHGs,"kg CO2e/2022 USD, purchaser price",0.429,0.059,0.488,111300

Ringkasan Jumlah Data:

                   Tahapan  Jumlah Baris  Jumlah Kolom
0  Sebelum Outlier Removal          1016             8
1  Setelah Outlier Removal           910             8

### 3. Data Preparation dengan Normalization

In [43]:
# 1. Import library yang diperlukan
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# 2. Load dataset
df = pd.read_csv("SupplyChainGHGEmissionFactors.csv")

# 3. Tampilkan data awal
print("Data Awal:")
display(df.head())

# 4. Pilih kolom numerik yang akan dinormalisasi
num_cols = [
    'Supply Chain Emission Factors without Margins',
    'Margins of Supply Chain Emission Factors',
    'Supply Chain Emission Factors with Margins'
]

# 5. Buat salinan data untuk dinormalisasi
df_normalized = df.copy()

# 6. Terapkan Normalization (Min-Max Scaling)
scaler = MinMaxScaler()
df_normalized[num_cols] = scaler.fit_transform(df_normalized[num_cols])

# 7. Tampilkan hasil normalisasi
print("Data Setelah Normalisasi (Min-Max Scaling):")
display(df_normalized.head())

# 8. Bandingkan sebelum dan sesudah dalam ringkasan
summary = pd.DataFrame({
    "Tahapan": ["Sebelum Normalisasi", "Setelah Normalisasi"],
    "Jumlah Baris": [df.shape[0], df_normalized.shape[0]],
    "Jumlah Kolom": [df.shape[1], df_normalized.shape[1]]
})
print("Ringkasan Jumlah Data:")
display(summary)

WARNING: Runtime no longer has a reference to this dataframe, please re-run this cell and try again.
Data Awal:

,2017 NAICS Code,2017 NAICS Title,GHG,Unit,Supply Chain Emission Factors without Margins,Margins of Supply Chain Emission Factors,Supply Chain Emission Factors with Margins,Reference USEEIO Code
0,111110,Soybean Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.488,0.044,0.532,1111A0
1,111120,Oilseed (except Soybean) Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.488,0.044,0.532,1111A0
2,111130,Dry Pea and Bean Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.809,0.040,0.848,1111B0
3,111140,Wheat Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.809,0.040,0.848,1111B0
4,111150,Corn Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.809,0.040,0.848,1111B0

Data Setelah Normalisasi (Min-Max Scaling):

,2017 NAICS Code,2017 NAICS Title,GHG,Unit,Supply Chain Emission Factors without Margins,Margins of Supply Chain Emission Factors,Supply Chain Emission Factors with Margins,Reference USEEIO Code
0,111110,Soybean Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.120942,0.352,0.12914,1111A0
1,111120,Oilseed (except Soybean) Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.120942,0.352,0.12914,1111A0
2,111130,Dry Pea and Bean Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.204974,0.320,0.21027,1111B0
3,111140,Wheat Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.204974,0.320,0.21027,1111B0
4,111150,Corn Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.204974,0.320,0.21027,1111B0

Ringkasan Jumlah Data:

               Tahapan  Jumlah Baris  Jumlah Kolom
0  Sebelum Normalisasi          1016             8
1  Setelah Normalisasi          1016             8

### 4. Data Preparation dengan Standarization

In [42]:
# 1. Import library yang dibutuhkan
import pandas as pd
from sklearn.preprocessing import StandardScaler

# 2. Load dataset
df = pd.read_csv("SupplyChainGHGEmissionFactors.csv")

# 3. Tampilkan data awal
print("Data Awal:")
display(df.head())

# 4. Pilih kolom numerik yang akan distandarisasi
num_cols = [
    'Supply Chain Emission Factors without Margins',
    'Margins of Supply Chain Emission Factors',
    'Supply Chain Emission Factors with Margins'
]

# 5. Buat salinan data
df_standardized = df.copy()

# 6. Terapkan Standardization (Z-score)
scaler = StandardScaler()
df_standardized[num_cols] = scaler.fit_transform(df_standardized[num_cols])

# 7. Tampilkan hasil standardisasi
print("Data Setelah Standardization (Z-score):")
display(df_standardized.head())

# 8. Ringkasan data sebelum dan sesudah
summary = pd.DataFrame({
    "Tahapan": ["Sebelum Standardisasi", "Setelah Standardisasi"],
    "Jumlah Baris": [df.shape[0], df_standardized.shape[0]],
    "Jumlah Kolom": [df.shape[1], df_standardized.shape[1]]
})
print("Ringkasan Jumlah Data:")
display(summary)

Data Awal:

,2017 NAICS Code,2017 NAICS Title,GHG,Unit,Supply Chain Emission Factors without Margins,Margins of Supply Chain Emission Factors,Supply Chain Emission Factors with Margins,Reference USEEIO Code
0,111110,Soybean Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.488,0.044,0.532,1111A0
1,111120,Oilseed (except Soybean) Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.488,0.044,0.532,1111A0
2,111130,Dry Pea and Bean Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.809,0.040,0.848,1111B0
3,111140,Wheat Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.809,0.040,0.848,1111B0
4,111150,Corn Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.809,0.040,0.848,1111B0

Data Setelah Standardization (Z-score):

,2017 NAICS Code,2017 NAICS Title,GHG,Unit,Supply Chain Emission Factors without Margins,Margins of Supply Chain Emission Factors,Supply Chain Emission Factors with Margins,Reference USEEIO Code
0,111110,Soybean Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.708825,1.158398,0.778508,1111A0
1,111120,Oilseed (except Soybean) Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.708825,1.158398,0.778508,1111A0
2,111130,Dry Pea and Bean Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",1.729126,0.987133,1.762140,1111B0
3,111140,Wheat Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",1.729126,0.987133,1.762140,1111B0
4,111150,Corn Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",1.729126,0.987133,1.762140,1111B0

Ringkasan Jumlah Data:

                 Tahapan  Jumlah Baris  Jumlah Kolom
0  Sebelum Standardisasi          1016             8
1  Setelah Standardisasi          1016             8

### 5. Pembuatan DataSet

In [44]:
# 1. Import library
import pandas as pd
from sklearn.model_selection import train_test_split

# 2. Load dataset
df = pd.read_csv("SupplyChainGHGEmissionFactors.csv")

# 3. Tampilkan beberapa data awal
print("Data Awal:")
display(df.head())

# 4. Pilih kolom fitur (X) dan target (y)
# Anggap kolom target adalah 'Supply Chain Emission Factors with Margins'
X = df.drop(columns=['Supply Chain Emission Factors with Margins'])
y = df['Supply Chain Emission Factors with Margins']

# 5. Lakukan One Hot Encoding pada fitur kategorikal
X = pd.get_dummies(X)

# 6. Split dataset menjadi training dan testing set (80:20)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 7. Tampilkan dimensi hasil split
summary = pd.DataFrame({
    "Dataset": ["Training Set", "Testing Set"],
    "Jumlah Baris": [X_train.shape[0], X_test.shape[0]],
    "Jumlah Kolom (fitur)": [X_train.shape[1], X_test.shape[1]]
})
print("Ringkasan Dataset:")
display(summary)

# 8. (Opsional) Gabungkan X dan y untuk melihat hasil akhir masing-masing set
train_set = pd.concat([X_train, y_train.reset_index(drop=True)], axis=1)
test_set = pd.concat([X_test, y_test.reset_index(drop=True)], axis=1)

# 9. Tampilkan contoh isi training dan testing set
print("Contoh Training Set:")
display(train_set.head())

print("Contoh Testing Set:")
display(test_set.head())

Data Awal:

,2017 NAICS Code,2017 NAICS Title,GHG,Unit,Supply Chain Emission Factors without Margins,Margins of Supply Chain Emission Factors,Supply Chain Emission Factors with Margins,Reference USEEIO Code
0,111110,Soybean Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.488,0.044,0.532,1111A0
1,111120,Oilseed (except Soybean) Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.488,0.044,0.532,1111A0
2,111130,Dry Pea and Bean Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.809,0.040,0.848,1111B0
3,111140,Wheat Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.809,0.040,0.848,1111B0
4,111150,Corn Farming,All GHGs,"kg CO2e/2022 USD, purchaser price",0.809,0.040,0.848,1111B0

Ringkasan Dataset:

        Dataset  Jumlah Baris  Jumlah Kolom (fitur)
0  Training Set           812                  1407
1   Testing Set           204                  1407

Contoh Training Set:

,2017 NAICS Code,Supply Chain Emission Factors without Margins,Margins of Supply Chain Emission Factors,2017 NAICS Title_Abrasive Product Manufacturing,2017 NAICS Title_Adhesive Manufacturing,2017 NAICS Title_Administrative Management and General Management Consulting Services,2017 NAICS Title_Advertising Agencies,2017 NAICS Title_Advertising Material Distribution Services,"2017 NAICS Title_Agents and Managers for Artists, Athletes, Entertainers, and Other Public Figures",2017 NAICS Title_Air Traffic Control,...,Reference USEEIO Code_811300,Reference USEEIO Code_811400,Reference USEEIO Code_812100,Reference USEEIO Code_812200,Reference USEEIO Code_812300,Reference USEEIO Code_812900,Reference USEEIO Code_813100,Reference USEEIO Code_813A00,Reference USEEIO Code_813B00,Supply Chain Emission Factors with Margins
332,332613.0,0.219,0.014,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0.246
708,519120.0,0.064,0.000,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0.128
218,322211.0,0.449,0.030,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0.078
425,335921.0,0.219,0.016,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0.111
448,336413.0,0.163,0.007,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,0.270

Contoh Testing Set:

,2017 NAICS Code,Supply Chain Emission Factors without Margins,Margins of Supply Chain Emission Factors,2017 NAICS Title_Abrasive Product Manufacturing,2017 NAICS Title_Adhesive Manufacturing,2017 NAICS Title_Administrative Management and General Management Consulting Services,2017 NAICS Title_Advertising Agencies,2017 NAICS Title_Advertising Material Distribution Services,"2017 NAICS Title_Agents and Managers for Artists, Athletes, Entertainers, and Other Public Figures",2017 NAICS Title_Air Traffic Control,...,Reference USEEIO Code_811300,Reference USEEIO Code_811400,Reference USEEIO Code_812100,Reference USEEIO Code_812200,Reference USEEIO Code_812300,Reference USEEIO Code_812900,Reference USEEIO Code_813100,Reference USEEIO Code_813A00,Reference USEEIO Code_813B00,Supply Chain Emission Factors with Margins
753,531120.0,0.246,0.000,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,NaN
519,423920.0,0.108,0.000,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,NaN
210,321920.0,0.135,0.029,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,NaN
943,713110.0,0.167,0.000,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,NaN
915,623220.0,0.129,0.000,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,NaN