<a href="https://colab.research.google.com/github/tommystarrrrrrr/2025_Kecerdasan-Buatan/blob/main/Data_Manipulation_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Jobsheet 5: Data Manipulation Pandas

## Import Library

In [15]:
import pandas as pd

## Load Dataset

In [17]:
df = pd.read_csv('./Data diri.csv')
df

     Negara    Umur        Gaji Transaksi
0   Jakarta    44.0   8000000.0     Tidak
1   Bandung    27.0   6700000.0        Ya
2  Surabaya    30.0   4500000.0     Tidak
3   Bandung    38.0   7500000.0     Tidak
4  Surabaya    40.0         NaN        Ya
5   Jakarta    35.0  10000000.0        Ya
6   Bandung     NaN   8250000.0     Tidak
7   Jakarta    48.0   9750000.0        Ya
8  Surabaya  1000.0   7674000.0     Tidak
9   Jakarta    27.0   6700000.0        Ya

In [18]:
df.isnull().sum()

Negara       0
Umur         1
Gaji         1
Transaksi    0
dtype: int64

## Mengatasi Missing Values dengan Drop Data

### 1. Hapus Data yang kosong (NaN)

In [19]:
df = pd.read_csv('./Data diri.csv')
df.dropna(inplace=True)

df

     Negara    Umur        Gaji Transaksi
0   Jakarta    44.0   8000000.0     Tidak
1   Bandung    27.0   6700000.0        Ya
2  Surabaya    30.0   4500000.0     Tidak
3   Bandung    38.0   7500000.0     Tidak
5   Jakarta    35.0  10000000.0        Ya
7   Jakarta    48.0   9750000.0        Ya
8  Surabaya  1000.0   7674000.0     Tidak
9   Jakarta    27.0   6700000.0        Ya

## Mengatasi Missing Values dengan Nilai Baru

### 2. Ganti Data yang kosong (NaN) menjadi :

### <ul><li>Umur = 50 </li><li>Gaji = 25000000</li></ul>

In [22]:
df = pd.read_csv('./Data diri.csv')
df['Umur'].fillna(50, inplace=True)
df['Gaji'].fillna(25000000, inplace=True)

<ipython-input-22-b66313effb3e>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Umur'].fillna(50, inplace=True)
<ipython-input-22-b66313effb3e>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gaji'].fillna(25000000, inplace=True)

In [23]:
df

     Negara    Umur        Gaji Transaksi
0   Jakarta    44.0   8000000.0     Tidak
1   Bandung    27.0   6700000.0        Ya
2  Surabaya    30.0   4500000.0     Tidak
3   Bandung    38.0   7500000.0     Tidak
4  Surabaya    40.0  25000000.0        Ya
5   Jakarta    35.0  10000000.0        Ya
6   Bandung    50.0   8250000.0     Tidak
7   Jakarta    48.0   9750000.0        Ya
8  Surabaya  1000.0   7674000.0     Tidak
9   Jakarta    27.0   6700000.0        Ya

## Mengatasi Missing Values dengan Nilai Mean

## 3. Ganti Data Kosong (NaN) pada Umur dan Gaji dengan Nilai Rata-Rata

In [24]:
df = pd.read_csv('./Data diri.csv')
mean_umur = df['Umur'].mean();
mean_gaji = df['Gaji'].mean();

df['Umur'].fillna(mean_umur, inplace=True)
df['Gaji'].fillna(mean_gaji, inplace=True)

<ipython-input-24-2126d590585c>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Umur'].fillna(mean_umur, inplace=True)
<ipython-input-24-2126d590585c>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gaji'].fillna(mean_gaji, inplace=True)

In [25]:
df

     Negara         Umur          Gaji Transaksi
0   Jakarta    44.000000  8.000000e+06     Tidak
1   Bandung    27.000000  6.700000e+06        Ya
2  Surabaya    30.000000  4.500000e+06     Tidak
3   Bandung    38.000000  7.500000e+06     Tidak
4  Surabaya    40.000000  7.674889e+06        Ya
5   Jakarta    35.000000  1.000000e+07        Ya
6   Bandung   143.222222  8.250000e+06     Tidak
7   Jakarta    48.000000  9.750000e+06        Ya
8  Surabaya  1000.000000  7.674000e+06     Tidak
9   Jakarta    27.000000  6.700000e+06        Ya

## Mengatasi Missing Values dengan Nilai Median

## 4. Ganti Data Kosong (NaN) pada Umur dan Gaji dengan Nilai Median

In [26]:
df = pd.read_csv('./Data diri.csv')
mean_umur = df['Umur'].median();
mean_gaji = df['Gaji'].median();

df['Umur'].fillna(mean_umur, inplace=True)
df['Gaji'].fillna(mean_gaji, inplace=True)

df

<ipython-input-26-ab1eb1f82c97>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Umur'].fillna(mean_umur, inplace=True)
<ipython-input-26-ab1eb1f82c97>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gaji'].fillna(mean_gaji, inplace=True)

     Negara    Umur        Gaji Transaksi
0   Jakarta    44.0   8000000.0     Tidak
1   Bandung    27.0   6700000.0        Ya
2  Surabaya    30.0   4500000.0     Tidak
3   Bandung    38.0   7500000.0     Tidak
4  Surabaya    40.0   7674000.0        Ya
5   Jakarta    35.0  10000000.0        Ya
6   Bandung    38.0   8250000.0     Tidak
7   Jakarta    48.0   9750000.0        Ya
8  Surabaya  1000.0   7674000.0     Tidak
9   Jakarta    27.0   6700000.0        Ya

## Mengatasi Missing Values dengan Nilai Mode

## 5. Ganti Data Kosong (NaN) pada Umur dan Gaji dengan Nilai Modus

In [27]:
df = pd.read_csv('./Data diri.csv')
mean_umur = df['Umur'].mode()[0];
mean_gaji = df['Gaji'].mode()[0];

df['Umur'].fillna(mean_umur, inplace=True)
df['Gaji'].fillna(mean_gaji, inplace=True)

df

<ipython-input-27-8fe0d7e896a1>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Umur'].fillna(mean_umur, inplace=True)
<ipython-input-27-8fe0d7e896a1>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gaji'].fillna(mean_gaji, inplace=True)

     Negara    Umur        Gaji Transaksi
0   Jakarta    44.0   8000000.0     Tidak
1   Bandung    27.0   6700000.0        Ya
2  Surabaya    30.0   4500000.0     Tidak
3   Bandung    38.0   7500000.0     Tidak
4  Surabaya    40.0   6700000.0        Ya
5   Jakarta    35.0  10000000.0        Ya
6   Bandung    27.0   8250000.0     Tidak
7   Jakarta    48.0   9750000.0        Ya
8  Surabaya  1000.0   7674000.0     Tidak
9   Jakarta    27.0   6700000.0        Ya

## Mengatasi Wrong Data dengan Ubah Data

## 6. Apabila Ada Umur yang diatas 120 maka ubah menjadi 33

In [28]:
df = pd.read_csv('./Data diri.csv')

for x in df.index:
    if df.loc[x, 'Umur'] > 120:
        df.loc[x, 'Umur'] = 33

df

     Negara  Umur        Gaji Transaksi
0   Jakarta  44.0   8000000.0     Tidak
1   Bandung  27.0   6700000.0        Ya
2  Surabaya  30.0   4500000.0     Tidak
3   Bandung  38.0   7500000.0     Tidak
4  Surabaya  40.0         NaN        Ya
5   Jakarta  35.0  10000000.0        Ya
6   Bandung   NaN   8250000.0     Tidak
7   Jakarta  48.0   9750000.0        Ya
8  Surabaya  33.0   7674000.0     Tidak
9   Jakarta  27.0   6700000.0        Ya

# PRAKTIKUM

In [2]:
# Import library
import pandas as pd

# Load dataset
customers = pd.read_csv('customers.csv')
gasstations = pd.read_csv('gasstations.csv')
products = pd.read_csv('products.csv')
transactions = pd.read_csv('transactions_1k.csv')
yearmonth = pd.read_csv('yearmonth.csv')

# Tambahkan kolom waktu
transactions['Date'] = pd.to_datetime(transactions['Date'])
transactions['DateTime'] = pd.to_datetime(transactions['Date'].astype(str) + ' ' + transactions['Time'])
transactions['Hour'] = transactions['DateTime'].dt.hour
transactions['Day'] = transactions['DateTime'].dt.day_name()

### 1. list Top 5 Customers yang memiliki nilai transaksi paling banyak

In [3]:
top_customers = (
    transactions.groupby('CustomerID')['Price']
    .sum()
    .sort_values(ascending=False)
    .head(5)
    .reset_index()
)
top_customers.columns = ['CustomerID', 'TotalTransactionValue']
top_customers

   CustomerID  TotalTransactionValue
0       19182                8618.54
1       16358                8400.94
2       31543                6161.50
3       12459                5974.47
4       30895                5940.01

### 2. list Top 5 Gas stations yang memiliki nilai transaksi paling banyak

In [4]:
top_gasstations = (
    transactions.groupby('GasStationID')['Price']
    .sum()
    .sort_values(ascending=False)
    .head(5)
    .reset_index()
)
top_gasstations.columns = ['GasStationID', 'TotalTransactionValue']
top_gasstations

   GasStationID  TotalTransactionValue
0          4347                8557.94
1            48                6868.67
2          3250                6744.47
3          1155                6701.69
4          2417                6065.16

### 3. list Top 5 Jenis produk yang memiliki nilai transaksi paling banyak

In [5]:
product_value = (
    transactions.groupby('ProductID')['Price']
    .sum()
    .sort_values(ascending=False)
    .head(5)
    .reset_index()
)
top_products = product_value.merge(products, on='ProductID')[['ProductID', 'Description', 'Price']]
top_products.rename(columns={'Price': 'TotalTransactionValue'}, inplace=True)
top_products

   ProductID Description  TotalTransactionValue
0          2       Nafta              345669.45
1          9    Diesel +               27261.03
2          5     Natural               24639.46
3         20  Nafta Plus                7233.72
4          8   Natural +                3999.92

### 4. deskripsi statistik untuk masing masing hari (23,24,25,26) pada dataset transaction_1k

In [7]:
filtered_days = transactions[transactions['Date'].dt.day.isin([23, 24, 25, 26])]
stats_per_day = filtered_days.groupby(filtered_days['Date'].dt.day)['Price'].describe()
stats_per_day

      count        mean         std    min      25%     50%      75%      max
Date
23     10.0  685.379000  534.046487  76.42  481.170  619.44  795.095  1994.71
24    492.0  409.939736  488.269481   1.76   76.125  332.45  615.395  5762.49
25    425.0  426.940071  453.134207   6.09  102.220  370.38  600.850  3600.84
26     73.0  487.431370  429.192499   4.74  142.840  437.03  675.520  2303.75

### 5. waktu terbaik (hari dan jam) dimana paling banyak user gas station melakukan transaksi

In [29]:
day_hour = transactions.groupby(['Day', 'Hour']).size().reset_index(name='TransactionCount')
best_time = day_hour.sort_values('TransactionCount', ascending=False).head(5)
best_time

         Day  Hour  TransactionCount
12    Friday    14                58
14    Friday    16                48
29  Saturday     8                47
32  Saturday    11                41
11    Friday    13                39

### 6. dari segi bisnis understanding, tujuan utama dari analisis data customer


Tujuan utama dari analisis data customer ini secara bisnis adalah:
- Mengidentifikasi pelanggan dengan nilai transaksi tertinggi untuk strategi loyalitas dan personalisasi penawaran.
- Mengoptimalkan performa stasiun pengisian berdasarkan pendapatan tertinggi.
- Menentukan jenis produk yang paling menguntungkan untuk perencanaan stok dan promosi.
- Mengetahui hari dan jam transaksi paling ramai untuk efisiensi operasional dan penempatan sumber daya.