<a href="https://colab.research.google.com/github/tommystarrrrrrr/2025_Kecerdasan-Buatan/blob/main/Pengolahan_Data_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# JOBSHEET 4: Pengolahan Data Menggunakan Pandas

## 1. membaca berbagai format file menggunakan pandass

### CSV

In [9]:
import pandas as pd

df = pd.read_csv('./data CSV.csv')
print(df.to_string())
df
pd.options.display.max_rows
pd.options.display.max_rows = 9999
df = pd.read_csv('./data CSV.csv')
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

### JSON

In [10]:
import pandas as pd

df = pd.read_json('./data file JSON.json')
print(df.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.5
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.5
37         60    100       120     300.1
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.1
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.4
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

### Menggunakan Parameter pada Pandas Read

In [11]:
df = pd.read_csv('./data CSV.csv', sep=',', header=0)
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

### Membaca costum data

In [2]:
data = {
  "Duration": {
    "0":60, "1":60, "2":60, "3":45
  },
  "Pulse": {
    "0":110, "1":117, "2":103, "3":109
  },
  "Maxpulse": {
    "0":130, "1":145, "2":135, "3":175
  },
  "Calories": {
    "0":409, "1":479, "2":340, "3":282
  }
}

df = pd.DataFrame(data)
print(df)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282

## 2. Membuat dan Mengakses Elemen Series

### Membuat Series dari sebuah List Python

In [1]:
import pandas as pd

li = [1, 7, 2]
se = pd.Series(li)

print(se)

0    1
1    7
2    2
dtype: int64

### Mengakses Elemen pada Series

In [12]:
li = [1, 7, 2]
se = pd.Series(li)

print(se[0])

1

### Memberi Label pada Series

In [13]:
li = [1, 7, 2]
se = pd.Series(li, index = ['x', 'y', 'z'])

print(se['x'])

1

### Membuat Series dari Dictionary

In [14]:
calories = {"day1": 420, "day2": 380, "day3": 390}
se = pd.Series(calories)

print(se)

day1    420
day2    380
day3    390
dtype: int64

## 3. membuat DataFrame

### membuat dataframe

In [15]:
import pandas as pd

df = pd.DataFrame(data= {
  "Nama" : ["Ali","Joko","Adi"],
  "Umur": [12, 13, 15],
  "Kelas": [6, 7, 8]
})

df.columns
df.columns.values[0] = "Nama Singkat"
df

  Nama Singkat  Umur  Kelas
0          Ali    12      6
1         Joko    13      7
2          Adi    15      8

In [16]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data)
df

   calories  duration
0       420        50
1       380        40
2       390        45

### Mengakses Elemen pada DataFrame

In [17]:
df.iloc[0:2, [0,1]]
df.iloc[0:2, 0:2]
df.iloc[:, 0:2]
df.loc[0:2, :'calories']
df.loc[0:2, ['calories', 'duration']]
df['calories']
df['calories'][0]
df[['calories']]
df[['calories']].loc[[0, 1]]

   calories
0       420
1       380

### memberi nama pada indeks

In [18]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ['day1', 'day2', 'day3'])
print(df)

      calories  duration
day1       420        50
day2       380        40
day3       390        45

### Melihat dataframe

In [20]:
df = pd.read_csv('./data CSV.csv')
print(df)

df
df.head()
df.tail()
df.head(10)
df.shape
df.dtypes

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

Duration      int64
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

### membaca informasi pada dataframe

In [21]:
df.info()
df.describe()
df['Calories'].mean(), df['Calories'].median(), df['Calories'].mode()[0]
df.corr()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB

          Duration     Pulse  Maxpulse  Calories
Duration  1.000000 -0.155408  0.009403  0.922717
Pulse    -0.155408  1.000000  0.786535  0.025121
Maxpulse  0.009403  0.786535  1.000000  0.203813
Calories  0.922717  0.025121  0.203813  1.000000

# Tugas Praktikum

1.

In [22]:
# Import library
import pandas as pd

# Load dataset
df = pd.read_csv('/content/epl-goalScorer(20-21).csv')

# TUGAS 1
print("Tugas 1 - DataFrame berhasil dibuat!")
print(df.head())

Tugas 1 - DataFrame berhasil dibuat!
   Unnamed: 0    id      player_name  games  time  goals         xG  assists  \
0           0   647       Harry Kane     35  3097     23  22.174859       14
1           1  1250    Mohamed Salah     37  3085     22  20.250847        5
2           2  1228  Bruno Fernandes     37  3117     18  16.019454       12
3           3   453    Son Heung-Min     37  3139     17  11.023287       10
4           4   822  Patrick Bamford     38  3085     17  18.401863        7

          xA  shots  key_passes  yellow_cards  red_cards position  \
0   7.577094    138          49             1          0        F
1   6.528526    126          55             0          0    F M S
2  11.474996    121          95             6          0      M S
3   9.512992     68          75             0          0    F M S
4   3.782247    107          30             3          0      F S

          team_title  npg       npxG    xGChain  xGBuildup
0          Tottenham   19  19.130183  24.995648   4.451257
1          Liverpool   16  15.683834  28.968234   9.800236
2  Manchester United    9   8.407840  26.911412  11.932285
3          Tottenham   16  10.262118  20.671916   6.608751
4              Leeds   15  16.879525  23.394953   4.131796

2.

In [23]:
# TUGAS 2: Ambil 5 data pertama
print("\nTugas 2 - 5 Data Pertama:")
print(df.head(5))

Tugas 2 - 5 Data Pertama:
   Unnamed: 0    id      player_name  games  time  goals         xG  assists  \
0           0   647       Harry Kane     35  3097     23  22.174859       14
1           1  1250    Mohamed Salah     37  3085     22  20.250847        5
2           2  1228  Bruno Fernandes     37  3117     18  16.019454       12
3           3   453    Son Heung-Min     37  3139     17  11.023287       10
4           4   822  Patrick Bamford     38  3085     17  18.401863        7

          xA  shots  key_passes  yellow_cards  red_cards position  \
0   7.577094    138          49             1          0        F
1   6.528526    126          55             0          0    F M S
2  11.474996    121          95             6          0      M S
3   9.512992     68          75             0          0    F M S
4   3.782247    107          30             3          0      F S

          team_title  npg       npxG    xGChain  xGBuildup
0          Tottenham   19  19.130183  24.995648   4.451257
1          Liverpool   16  15.683834  28.968234   9.800236
2  Manchester United    9   8.407840  26.911412  11.932285
3          Tottenham   16  10.262118  20.671916   6.608751
4              Leeds   15  16.879525  23.394953   4.131796

3.

In [24]:
# TUGAS 3: Tampilkan jumlah baris dan kolom
print("\nTugas 3 - Jumlah Baris dan Kolom:")
print(f"Jumlah baris: {df.shape[0]}")
print(f"Jumlah kolom: {df.shape[1]}")

Tugas 3 - Jumlah Baris dan Kolom:
Jumlah baris: 522
Jumlah kolom: 19

4.

In [25]:
# TUGAS 4: Tampilkan tipe data dari masing-masing kolom
print("\nTugas 4 - Tipe Data Kolom:")
print(df.dtypes)

Tugas 4 - Tipe Data Kolom:
Unnamed: 0        int64
id                int64
player_name      object
games             int64
time              int64
goals             int64
xG              float64
assists           int64
xA              float64
shots             int64
key_passes        int64
yellow_cards      int64
red_cards         int64
position         object
team_title       object
npg               int64
npxG            float64
xGChain         float64
xGBuildup       float64
dtype: object

5.

In [26]:
print("--- Jumlah goal setiap pemain ---")
print(df[['player_name', 'goals']])

--- Jumlah goal setiap pemain ---
                   player_name  goals
0                   Harry Kane     23
1                Mohamed Salah     22
2              Bruno Fernandes     18
3                Son Heung-Min     17
4              Patrick Bamford     17
5        Dominic Calvert-Lewin     16
6                  Jamie Vardy     15
7                Ollie Watkins     14
8               Ilkay Gündogan     13
9          Alexandre Lacazette     13
10               Callum Wilson     12
11           Kelechi Iheanacho     12
12                  Danny Ings     12
13                  Chris Wood     12
14               Wilfried Zaha     11
15             Marcus Rashford     11
16                  Sadio Mané     11
17                 Gareth Bale     11
18             Matheus Pereira     11
19   Pierre-Emerick Aubameyang     10
20             Michail Antonio     10
21           Christian Benteke     10
22             Raheem Sterling     10
23              Edinson Cavani     10
24              Anwar El Ghazi     10
25                Tomas Soucek     10
26             Roberto Firmino      9
27               Jesse Lingard      9
28                Riyad Mahrez      9
29               Harvey Barnes      9
30                  Diogo Jota      9
31                   Che Adams      9
32           James Ward-Prowse      8
33                Jarrod Bowen      8
34                 Neal Maupay      8
35               Gabriel Jesus      8
36                Nicolas Pepe      8
37                  Phil Foden      8
38                 Joe Willock      8
39              James Maddison      8
40               Stuart Dallas      8
41               Jack Harrison      8
42             Bertrand Traoré      7
43                    Jorginho      7
44                     Rodrigo      7
45                 Richarlison      7
46               Ferrán Torres      7
47             Mason Greenwood      7
48            David McGoldrick      7
49                 Timo Werner      6
50               Danny Welbeck      6
51               Jack Grealish      6
52               Tammy Abraham      6
53            Gylfi Sigurdsson      6
54             James Rodríguez      6
55             Youri Tielemans      6
56                 Mason Mount      6
57                    Raphinha      6
58             Kevin De Bruyne      5
59                  Kurt Zouma      5
60             Callum Robinson      5
61                  Lewis Dunk      5
62                  Pedro Neto      5
63                  Bobby Reid      5
64                 Rúben Neves      5
65                 Bukayo Saka      5
66            Leandro Trossard      5
67                   Joelinton      4
68              Olivier Giroud      4
69             Anthony Martial      4
70                 John Stones      4
71           Christian Pulisic      4
72                Raúl Jiménez      4
73               Mateusz Klich      4
74                 Kai Havertz      4
75             Ademola Lookman      4
76             Scott McTominay      4
77            Stuart Armstrong      4
78              Miguel Almirón      4
79                Eberechi Eze      4
80                 Fabio Silva      4
81         Allan Saint-Maximin      3
82          Jannik Vestergaard      3
83                 Pascal Groß      3
84                Theo Walcott      3
85              Angelo Ogbonna      3
86                Ross Barkley      3
87             Ashley Westwood      3
88         Aleksandar Mitrovic      3
89                Ben Chilwell      3
90                Craig Dawson      3
91                Kyle Bartley      3
92                 Matej Vydra      3
93               Michael Keane      3
94                  Paul Pogba      3
95               Pablo Fornals      3
96                 Lucas Moura      3
97                Hélder Costa      3
98                Romain Saiss      3
99              Ivan Cavaleiro      3
100              Ashley Barnes      3
101                  Josh Maja      3
102               Daniel James      3
103     Tanguy NDombele Alvaro      3
104           Sébastien Haller      3
105                Billy Sharp      3
106                John McGinn      3
107            Takumi Minamino      3
108             Daniel Podence      3
109               Mbaye Diagne      3
110      Pierre-Emile Højbjerg      2
111              Sergio Agüero      2
112                   Ola Aina      2
113            Jeffrey Schlupp      2
114           Jamaal Lascelles      2
115                Ayoze Pérez      2
116        Georginio Wijnaldum      2
117             Nathan Redmond      2
118                Jonny Evans      2
119               Adama Traoré      2
120               Tyrone Mings      2
121              Marcos Alonso      2
122                    Ben Mee      2
123    Johann Berg Gudmundsson      2
124            Michy Batshuayi      2
125              Harry Maguire      2
126         Abdoulaye Doucouré      2
127              Matt Phillips      2
128            Hal Robson-Kanu      2
129              Jeff Hendrick      2
130     Trent Alexander-Arnold      2
131               João Cancelo      2
132                      Rodri      2
133                  Issa Diop      2
134               Thiago Silva      2
135             Benjamin Mendy      2
136               Serge Aurier      2
137             Bernardo Silva      2
138                 Semi Ajayi      2
139          Aaron Wan-Bissaka      2
140                    Gabriel      2
141            Jairo Riedewald      2
142                Solly March      2
143               Jacob Murphy      2
144           Timothy Castagne      2
145         Callum Hudson-Odoi      2
146              Eddie Nketiah      2
147                 Yerry Mina      2
148              Dwight McNeil      2
149           Emile Smith-Rowe      2
150                  Trézéguet      2
151           Ezri Konsa Ngoyo      2
152         Gabriel Martinelli      2
153               James Justin      2
154             Aaron Connolly      2
155             Ezgjan Alioski      2
156               Hakim Ziyech      2
157            Conor Gallagher      2
158               Jayden Bogle      2
159               Fabian Schär      1
160               Granit Xhaka      1
161           Thiago Alcántara      1
162                 Joel Matip      1
163               Adam Lallana      1
164            Héctor Bellerín      1
165             Mohamed Elneny      1
166                 Alex Iwobi      1
167                 Scott Dann      1
168           Cheikhou Kouyaté      1
169             Manuel Lanzini      1
170               Andy Carroll      1
171                 Nathan Aké      1
172           Jordan Henderson      1
173                Kyle Walker      1
174          Toby Alderweireld      1
175                Erik Lamela      1
176                Jordan Ayew      1
177          César Azpilicueta      1
178         Ruben Loftus-Cheek      1
179                Gary Cahill      1
180                    Willian      1
181               Dwight Gayle      1
182            Marc Albrighton      1
183             Daniel Amartey      1
184              Jonjo Shelvey      1
185            Andros Townsend      1
186               Robbie Brady      1
187            Virgil van Dijk      1
188                Oriol Romeu      1
189              Jay Rodriguez      1
190               Paul Dummett      1
191               Ciaran Clark      1
192    Alex Oxlade-Chamberlain      1
193              Mason Holgate      1
194                  Luke Shaw      1
195              Tyler Roberts      1
196               Keinan Davis      1
197               Dennis Praet      1
198                    Alisson      1
199               Mario Lemina      1
200                Emil Krafth      1
201             Matthew Lowton      1
202            James Tarkowski      1
203                 David Luiz      1
204           Andrew Robertson      1
205            Oliver McBurnie      1
206            Antonio Rüdiger      1
207             Diego Llorente      1
208               Willian José      1
209            Martin Odegaard      1
210              João Moutinho      1
211              Said Benrahma      1
212            Darnell Furlong      1
213               Oliver Burke      1
214             Caglar Söyüncü      1
215              Wilfred Ndidi      1
216           Luka Milivojevic      1
217                Declan Rice      1
218              Yves Bissouma      1
219           Giovani Lo Celso      1
220       Jean-Philippe Mateta      1
221               Jan Bednarek      1
222            Victor Lindelöf      1
223           Joachim Andersen      1
224                Ben Johnson      1
225             Grady Diangana      1
226               Curtis Jones      1
227            Rayan Ait Nouri      1
228                       Fred      1
229                  Joe Bryan      1
230                Tom Cairney      1
231                 Willy Boly      1
232                Conor Coady      1
233         Morgan Gibbs-White      1
234              Kortney Hause      1
235            Ryan Fredericks      1
236            Fabián Balbuena      1
237                    Bernard      1
238         Leander Dendoncker      1
239                   Dan Burn      1
240               Karlan Grant      1
241            Carlos Vinicius      1
242               Adam Webster      1
243             Moussa Djenepo      1
244                 Ben Osborn      1
245            Conor Hourihane      1
246              Steven Alzate      1
247                Reece James      1
248             Kieran Tierney      1
249            Tyrick Mitchell      1
250              Tariq Lamptey      1
251         Nathaniel Phillips      1
252               Sander Berge      1
253            Steven Bergwijn      1
254        Alexis Mac Allister      1
255               Nathan Tella      1
256                Jimmy Dunne      1
257                Luke Thomas      1
258             Pascal Struijk      1
259            Kalvin Phillips      1
260               Joël Veltman      1
261                Liam Cooper      1
262          Donny van de Beek      1
263                 Rúben Dias      1
264                 Kean Bryan      1
265             Fabio Carvalho      1
266            Daniel Jebbison      1
267                 Bernd Leno      0
268        Andreas Christensen      0
269             Sead Kolasinac      0
270               Matt Ritchie      0
271                Joshua King      0
272               Divock Origi      0
273              Mamadou Sakho      0
274               James Milner      0
275             Calum Chambers      0
276                  Joel Ward      0
277               Martin Kelly      0
278                     Adrián      0
279              James Tomkins      0
280                 Mark Noble      0
281            Aaron Cresswell      0
282            Darren Randolph      0
283               Kieran Gibbs      0
284               David de Gea      0
285        Timothy Fosu-Mensah      0
286                  Juan Mata      0
287               Odion Ighalo      0
288             Seamus Coleman      0
289              Phil Jagielka      0
290             James McCarthy      0
291            Nathaniel Clyne      0
292                Fernandinho      0
293            Willy Caballero      0
294             James McArthur      0
295              Alex McCarthy      0
296                Hugo Lloris      0
297                  Eric Dier      0
298                  Dele Alli      0
299                 Ben Davies      0
300                Josh Onomah      0
301         Branislav Ivanovic      0
302              Nemanja Matic      0
303              Fikayo Tomori      0
304           Lukasz Fabianski      0
305         Federico Fernández      0
306                Neil Taylor      0
307                  Jack Cork      0
308             DeAndre Yedlin      0
309        Patrick van Aanholt      0
310            Jordan Pickford      0
311          Kasper Schmeichel      0
312                 Wes Morgan      0
313            Christian Fuchs      0
314          N&#039;Golo Kanté      0
315               Demarai Gray      0
316             Moussa Sissoko      0
317                Karl Darlow      0
318                 John Ruddy      0
319             Fraser Forster      0
320              Ryan Bertrand      0
321                 Shane Long      0
322              Cédric Soares      0
323             Charlie Austin      0
324               Jack Butland      0
325              Phil Bardsley      0
326               Fabian Delph      0
327               Matt Targett      0
328         Kyle Walker-Peters      0
329               Erik Pieters      0
330            Xherdan Shaqiri      0
331              Harrison Reed      0
332              Axel Tuanzebe      0
333                Harry Winks      0
334              Sam Johnstone      0
335               Joseph Gomez      0
336                  Sam Field      0
337                 Tom Davies      0
338               Jonjoe Kenny      0
339            Felipe Anderson      0
340                    Emerson      0
341                 Moise Kean      0
342                      Allan      0
343              Islam Slimani      0
344                Ryan Fraser      0
345           Ahmed Elmohamady      0
346             Jake Livermore      0
347           Robert Snodgrass      0
348           Shkodran Mustafi      0
349           Javier Manquillo      0
350              Jack Stephens      0
351                Eric Bailly      0
352                 Kevin Long      0
353                Lys Mousset      0
354                Rob Holding      0
355     Ainsley Maitland-Niles      0
356             Arthur Masuaku      0
357             Nampalys Mendy      0
358                Lucas Digne      0
359                Alex Telles      0
360            Pablo Hernández      0
361             Vicente Guaita      0
362              Mateo Kovacic      0
363               Kiko Casilla      0
364                      Jonny      0
365            Alphonse Areola      0
366              Thomas Partey      0
367                André Gomes      0
368                   Mat Ryan      0
369              Dani Ceballos      0
370            Aymeric Laporte      0
371        Oleksandr Zinchenko      0
372             Kamil Grosicki      0
373            Ricardo Pereira      0
374         Maxime Le Marchand      0
375                    Fabinho      0
376              Morgan Sanson      0
377               Ahmed Hegazy      0
378          Emiliano Martinez      0
379       Jean-Philippe Gbamin      0
380           Aboubakar Kamara      0
381            Patrick Cutrone      0
382                       Kepa      0
383                   Bernardo      0
384                 Naby Keita      0
385             Michael Hector      0
386                  Nick Pope      0
387              Rekeem Harper      0
388             Rhian Brewster      0
389           Tosin Adarabioyo      0
390             Aaron Ramsdale      0
391            Fernando Marçal      0
392                 Kenny Tete      0
393             Charlie Taylor      0
394               Davy Pröpper      0
395              Dale Stephens      0
396                    Ederson      0
397               Isaac Hayden      0
398            Terence Kongolo      0
399               Douglas Luiz      0
400               Cengiz Ünder      0
401              Nélson Semedo      0
402             José Izquierdo      0
403           Davinson Sánchez      0
404                 Robin Koch      0
405          Andriy Yarmolenko      0
406             Jayson Molumby      0
407               Ethan Ampadu      0
408                  Joe Rodon      0
409            Hamza Choudhury      0
410               Franck Zambo      0
411                 Cenk Tosun      0
412               Reiss Nelson      0
413            Michael Obafemi      0
414            Martin Dubravka      0
415            Ibrahima Diallo      0
416                Lee Peltier      0
417            Neeskens Kebano      0
418        Alireza Jahanbakhsh      0
419               David Button      0
420               Rui Patrício      0
421               Matt Doherty      0
422              Rúben Vinagre      0
423       Rúnar Alex Rúnarsson      0
424              Edouard Mendy      0
425            Mohammed Salisu      0
426               Okay Yokuslu      0
427                Robin Olsen      0
428                 Denis Odoi      0
429             Sean Longstaff      0
430                   Tim Ream      0
431            Sergio Reguilón      0
432                 Yan Valery      0
433                  Ben White      0
434               Kayne Ramsay      0
435                 Max Kilman      0
436                 Ozan Kabak      0
437                Josh Benson      0
438                Will Norris      0
439              Wesley Fofana      0
440                Ben Godfrey      0
441                Jamal Lewis      0
442             Dean Henderson      0
443                  John Egan      0
444               Chris Basham      0
445        Jack O&#039;Connell      0
446             George Baldock      0
447               Enda Stevens      0
448             John Lundstram      0
449                 John Fleck      0
450             Oliver Norwood      0
451                     Wesley      0
452               Zack Steffen      0
453          Caoimhin Kelleher      0
454      Daniel N&#039;Lundulu      0
455              Billy Gilmour      0
456          Matthew Longstaff      0
457          Marvelous Nakamba      0
458                Eric Garcia      0
459           Brandon Williams      0
460             Niels Nkounkou      0
461         Amad Diallo Traore      0
462             Anthony Gordon      0
463               Scott Carson      0
464              Owen Otasowie      0
465              Neco Williams      0
466            Japhet Tanganga      0
467          William Smallbone      0
468                 Oskar Buur      0
469              Jack Robinson      0
470             Josh Brownhill      0
471             Ki-Jana Hoever      0
472              João Virgínia      0
473                 Pablo Marí      0
474     Bailey Peacock-Farrell      0
475                Jake Vokins      0
476        Alexandre Jankewitz      0
477              Joel Mumbongo      0
478                Marek Rodák      0
479              Illan Meslier      0
480                Luke Ayling      0
481           Jamie Shackleton      0
482          Ian Poveda-Ocampo      0
483           Dara O&#039;Shea      0
484            Romaine Sawyers      0
485               Kyle Edwards      0
486                    Vitinha      0
487      Konstantinos Tsimikas      0
488               Matthew Cash      0
489                 Liam Delap      0
490             Conor Townsend      0
491                   Max Lowe      0
492                 Leif Davis      0
493           Antonee Robinson      0
494               Jacob Ramsey      0
495            Vladimir Coufal      0
496           Filip Krovinovic      0
497           Lewis Richardson      0
498              Rhys Williams      0
499             Robert Sánchez      0
500                Andi Zeqiri      0
501            Elliot Anderson      0
502              Theo Corbeanu      0
503              Niall Huggins      0
504          Antwoine Hackford      0
505                  Percy Tau      0
506                Reda Khadra      0
507                Caleb Watts      0
508           Allan Tchaptchet      0
509                Jakub Moder      0
510              Iliman Ndiaye      0
511         Thakgalo Leshabela      0
512              Dane Scarlett      0
513         Carney Chukwuemeka      0
514            Shola Shoretire      0
515             Sidnei Tavares      0
516           Nathan Broadhead      0
517     Jaden Philogene-Bidace      0
518            Gaetano Berardi      0
519             Anthony Elanga      0
520                Femi Seriki      0
521            Tyrese Francois      0

6.

In [27]:
selected_columns = df[['player_name', 'goals', 'position', 'team_title', 'yellow_cards']]
print(selected_columns.to_string(index=False))

              player_name  goals position                    team_title  yellow_cards
               Harry Kane     23        F                     Tottenham             1
            Mohamed Salah     22    F M S                     Liverpool             0
          Bruno Fernandes     18      M S             Manchester United             6
            Son Heung-Min     17    F M S                     Tottenham             0
          Patrick Bamford     17      F S                         Leeds             3
    Dominic Calvert-Lewin     16      F S                       Everton             3
              Jamie Vardy     15      F S                     Leicester             1
            Ollie Watkins     14        F                   Aston Villa             2
           Ilkay Gündogan     13      M S               Manchester City             1
      Alexandre Lacazette     13    F M S                       Arsenal             3
            Callum Wilson     12      F S              Newcastle United             2
        Kelechi Iheanacho     12      F S                     Leicester             1
               Danny Ings     12      F S                   Southampton             1
               Chris Wood     12      F S                       Burnley             0
            Wilfried Zaha     11    F M S                Crystal Palace             6
          Marcus Rashford     11    F M S             Manchester United             4
               Sadio Mané     11    F M S                     Liverpool             3
              Gareth Bale     11      M S                     Tottenham             1
          Matheus Pereira     11      M S          West Bromwich Albion             2
Pierre-Emerick Aubameyang     10    F M S                       Arsenal             2
          Michail Antonio     10      F S                      West Ham             3
        Christian Benteke     10      F S                Crystal Palace             1
          Raheem Sterling     10    F M S               Manchester City             3
           Edinson Cavani     10      F S             Manchester United             4
           Anwar El Ghazi     10    F M S                   Aston Villa             2
             Tomas Soucek     10        M                      West Ham             7
          Roberto Firmino      9    F M S                     Liverpool             2
            Jesse Lingard      9      F M                      West Ham             3
             Riyad Mahrez      9    F M S               Manchester City             0
            Harvey Barnes      9    F M S                     Leicester             0
               Diogo Jota      9    F M S                     Liverpool             2
                Che Adams      9      F S                   Southampton             1
        James Ward-Prowse      8      D M                   Southampton             5
             Jarrod Bowen      8    F M S                      West Ham             0
              Neal Maupay      8    F M S                      Brighton             1
            Gabriel Jesus      8    F M S               Manchester City             2
             Nicolas Pepe      8    F M S                       Arsenal             1
               Phil Foden      8    F M S               Manchester City             0
              Joe Willock      8      M S      Arsenal,Newcastle United             1
           James Maddison      8      M S                     Leicester             4
            Stuart Dallas      8      D M                         Leeds             7
            Jack Harrison      8      M S                         Leeds             2
          Bertrand Traoré      7    F M S                   Aston Villa             1
                 Jorginho      7      M S                       Chelsea             2
                  Rodrigo      7    F M S                         Leeds             3
              Richarlison      7    F M S                       Everton             3
            Ferrán Torres      7    F M S               Manchester City             1
          Mason Greenwood      7    F M S             Manchester United             2
         David McGoldrick      7    F M S              Sheffield United             7
              Timo Werner      6    F M S                       Chelsea             2
            Danny Welbeck      6    F M S                      Brighton             0
            Jack Grealish      6    F M S                   Aston Villa             5
            Tammy Abraham      6      F S                       Chelsea             0
         Gylfi Sigurdsson      6    F M S                       Everton             2
          James Rodríguez      6    F M S                       Everton             4
          Youri Tielemans      6      M S                     Leicester             6
              Mason Mount      6    F M S                       Chelsea             2
                 Raphinha      6      M S                         Leeds             3
          Kevin De Bruyne      5      M S               Manchester City             1
               Kurt Zouma      5      D S                       Chelsea             3
          Callum Robinson      5    F M S          West Bromwich Albion             0
               Lewis Dunk      5        D                      Brighton             5
               Pedro Neto      5    F M S       Wolverhampton Wanderers             4
               Bobby Reid      5  D F M S                        Fulham             7
              Rúben Neves      5      M S       Wolverhampton Wanderers             7
              Bukayo Saka      5  D F M S                       Arsenal             1
         Leandro Trossard      5    F M S                      Brighton             2
                Joelinton      4    F M S              Newcastle United             3
           Olivier Giroud      4      F S                       Chelsea             1
          Anthony Martial      4    F M S             Manchester United             0
              John Stones      4        D               Manchester City             0
        Christian Pulisic      4    F M S                       Chelsea             2
             Raúl Jiménez      4        F       Wolverhampton Wanderers             0
            Mateusz Klich      4      M S                         Leeds             6
              Kai Havertz      4    F M S                       Chelsea             2
          Ademola Lookman      4    F M S                        Fulham             5
          Scott McTominay      4      M S             Manchester United             3
         Stuart Armstrong      4      M S                   Southampton             3
           Miguel Almirón      4    F M S              Newcastle United             3
             Eberechi Eze      4      M S                Crystal Palace             3
              Fabio Silva      4      F S       Wolverhampton Wanderers             2
      Allan Saint-Maximin      3    F M S              Newcastle United             0
       Jannik Vestergaard      3      D S                   Southampton             3
              Pascal Groß      3    D M S                      Brighton             3
             Theo Walcott      3    F M S           Everton,Southampton             0
           Angelo Ogbonna      3        D                      West Ham             5
             Ross Barkley      3      M S           Aston Villa,Chelsea             0
          Ashley Westwood      3        M                       Burnley             7
      Aleksandar Mitrovic      3      F S                        Fulham             3
             Ben Chilwell      3      D M                       Chelsea             3
             Craig Dawson      3        D                      West Ham             3
             Kyle Bartley      3      D S          West Bromwich Albion             4
              Matej Vydra      3      F S                       Burnley             0
            Michael Keane      3      D S                       Everton             4
               Paul Pogba      3      M S             Manchester United             3
            Pablo Fornals      3    F M S                      West Ham             3
              Lucas Moura      3    F M S                     Tottenham             1
             Hélder Costa      3      M S                         Leeds             0
             Romain Saiss      3        D       Wolverhampton Wanderers             2
           Ivan Cavaleiro      3  D F M S                        Fulham             2
            Ashley Barnes      3    F M S                       Burnley             4
                Josh Maja      3      F S                        Fulham             0
             Daniel James      3      M S             Manchester United             3
   Tanguy NDombele Alvaro      3      M S                     Tottenham             3
         Sébastien Haller      3      F S                      West Ham             0
              Billy Sharp      3      F S              Sheffield United             1
              John McGinn      3        M                   Aston Villa            12
          Takumi Minamino      3    F M S         Liverpool,Southampton             1
           Daniel Podence      3    F M S       Wolverhampton Wanderers             3
             Mbaye Diagne      3      F S          West Bromwich Albion             2
    Pierre-Emile Højbjerg      2        M                     Tottenham             9
            Sergio Agüero      2    F M S               Manchester City             0
                 Ola Aina      2      D M                        Fulham             3
          Jeffrey Schlupp      2      M S                Crystal Palace             3
         Jamaal Lascelles      2        D              Newcastle United             4
              Ayoze Pérez      2    F M S                     Leicester             2
      Georginio Wijnaldum      2      M S                     Liverpool             1
           Nathan Redmond      2    F M S                   Southampton             1
              Jonny Evans      2        D                     Leicester             7
             Adama Traoré      2  D F M S       Wolverhampton Wanderers             4
             Tyrone Mings      2        D                   Aston Villa             4
            Marcos Alonso      2      D S                       Chelsea             2
                  Ben Mee      2        D                       Burnley             3
  Johann Berg Gudmundsson      2      M S                       Burnley             2
          Michy Batshuayi      2      F S                Crystal Palace             0
            Harry Maguire      2        D             Manchester United            11
       Abdoulaye Doucouré      2        M                       Everton             6
            Matt Phillips      2      M S          West Bromwich Albion             1
          Hal Robson-Kanu      2      F S          West Bromwich Albion             2
            Jeff Hendrick      2      M S              Newcastle United             1
   Trent Alexander-Arnold      2      D S                     Liverpool             2
             João Cancelo      2    D M S               Manchester City             5
                    Rodri      2      M S               Manchester City             6
                Issa Diop      2      D S                      West Ham             3
             Thiago Silva      2        D                       Chelsea             3
           Benjamin Mendy      2    D M S               Manchester City             2
             Serge Aurier      2      D M                     Tottenham             0
           Bernardo Silva      2    F M S               Manchester City             5
               Semi Ajayi      2      D S          West Bromwich Albion             3
        Aaron Wan-Bissaka      2        D             Manchester United             3
                  Gabriel      2      D S                       Arsenal             2
          Jairo Riedewald      2      M S                Crystal Palace             4
              Solly March      2    D M S                      Brighton             0
             Jacob Murphy      2    D M S              Newcastle United             3
         Timothy Castagne      2      D M                     Leicester             1
       Callum Hudson-Odoi      2  D F M S                       Chelsea             0
            Eddie Nketiah      2      F S                       Arsenal             0
               Yerry Mina      2      D S                       Everton             2
            Dwight McNeil      2      M S                       Burnley             1
         Emile Smith-Rowe      2      M S                       Arsenal             0
                Trézéguet      2    F M S                   Aston Villa             0
         Ezri Konsa Ngoyo      2      D S                   Aston Villa             3
       Gabriel Martinelli      2    F M S                       Arsenal             0
             James Justin      2        D                     Leicester             4
           Aaron Connolly      2    F M S                      Brighton             0
           Ezgjan Alioski      2    D M S                         Leeds             7
             Hakim Ziyech      2    F M S                       Chelsea             3
          Conor Gallagher      2      M S          West Bromwich Albion            11
             Jayden Bogle      2    D M S              Sheffield United             2
             Fabian Schär      1      D S              Newcastle United             4
             Granit Xhaka      1    D M S                       Arsenal             7
         Thiago Alcántara      1      M S                     Liverpool             4
               Joel Matip      1      D S                     Liverpool             2
             Adam Lallana      1    F M S                      Brighton             0
          Héctor Bellerín      1      D S                       Arsenal             8
           Mohamed Elneny      1      M S                       Arsenal             3
               Alex Iwobi      1  D F M S                       Everton             0
               Scott Dann      1        D                Crystal Palace             1
         Cheikhou Kouyaté      1    D M S                Crystal Palace             4
           Manuel Lanzini      1      M S                      West Ham             1
             Andy Carroll      1      F S              Newcastle United             1
               Nathan Aké      1      D S               Manchester City             4
         Jordan Henderson      1    D M S                     Liverpool             0
              Kyle Walker      1      D S               Manchester City             1
        Toby Alderweireld      1        D                     Tottenham             2
              Erik Lamela      1    F M S                     Tottenham             4
              Jordan Ayew      1    F M S                Crystal Palace             4
        César Azpilicueta      1      D S                       Chelsea             5
       Ruben Loftus-Cheek      1    F M S                Chelsea,Fulham             3
              Gary Cahill      1        D                Crystal Palace             3
                  Willian      1    F M S                       Arsenal             0
             Dwight Gayle      1      F S              Newcastle United             0
          Marc Albrighton      1    D M S                     Leicester             2
           Daniel Amartey      1      D S                     Leicester             2
            Jonjo Shelvey      1      M S              Newcastle United             7
          Andros Townsend      1    F M S                Crystal Palace             0
             Robbie Brady      1      M S                       Burnley             3
          Virgil van Dijk      1        D                     Liverpool             1
              Oriol Romeu      1        M                   Southampton             6
            Jay Rodriguez      1    F M S                       Burnley             3
             Paul Dummett      1      D S              Newcastle United             2
             Ciaran Clark      1      D S              Newcastle United             3
  Alex Oxlade-Chamberlain      1    F M S                     Liverpool             0
            Mason Holgate      1    D M S                       Everton             8
                Luke Shaw      1      D S             Manchester United             8
            Tyler Roberts      1    F M S                         Leeds             3
             Keinan Davis      1      F S                   Aston Villa             0
             Dennis Praet      1      M S                     Leicester             0
                  Alisson      1       GK                     Liverpool             1
             Mario Lemina      1    D M S                        Fulham             5
              Emil Krafth      1      D S              Newcastle United             4
           Matthew Lowton      1        D                       Burnley             5
          James Tarkowski      1        D                       Burnley             6
               David Luiz      1      D S                       Arsenal             1
         Andrew Robertson      1        D                     Liverpool             2
          Oliver McBurnie      1      F S              Sheffield United             2
          Antonio Rüdiger      1        D                       Chelsea             0
           Diego Llorente      1      D S                         Leeds             1
             Willian José      1      F S       Wolverhampton Wanderers             0
          Martin Odegaard      1      M S                       Arsenal             0
            João Moutinho      1      M S       Wolverhampton Wanderers             3
            Said Benrahma      1      M S                      West Ham             0
          Darnell Furlong      1    D M S          West Bromwich Albion             5
             Oliver Burke      1      F S              Sheffield United             2
           Caglar Söyüncü      1      D S                     Leicester             2
            Wilfred Ndidi      1    D M S                     Leicester             6
         Luka Milivojevic      1      M S                Crystal Palace             8
              Declan Rice      1        M                      West Ham             2
            Yves Bissouma      1      M S                      Brighton             8
         Giovani Lo Celso      1      M S                     Tottenham             5
     Jean-Philippe Mateta      1      F S                Crystal Palace             0
             Jan Bednarek      1        D                   Southampton             4
          Victor Lindelöf      1        D             Manchester United             0
         Joachim Andersen      1      D S                        Fulham             7
              Ben Johnson      1    D M S                      West Ham             1
           Grady Diangana      1    F M S          West Bromwich Albion             0
             Curtis Jones      1      M S                     Liverpool             2
          Rayan Ait Nouri      1    D M S       Wolverhampton Wanderers             0
                     Fred      1      M S             Manchester United             5
                Joe Bryan      1    D M S                        Fulham             2
              Tom Cairney      1      M S                        Fulham             2

7.

In [28]:
print("Pemain Liverpool:")
print(df[df['team_title'] == 'Liverpool'])

Pemain Liverpool:
     Unnamed: 0    id              player_name  games  time  goals         xG  \
1             1  1250            Mohamed Salah     37  3085     22  20.250847
16           16   838               Sadio Mané     35  2805     11  14.828548
26           26   482          Roberto Firmino     36  2882      9  12.860213
30           30  6854               Diogo Jota     19  1114      9   7.057721
116         116   771      Georginio Wijnaldum     38  2961      2   2.817427
130         130  1791   Trent Alexander-Arnold     36  3040      2   2.593060
161         161   229         Thiago Alcántara     24  1865      1   1.211306
162         162   332               Joel Matip     10   701      1   0.784475
172         172   605         Jordan Henderson     21  1710      1   1.135798
187         187   833          Virgil van Dijk      5   370      1   0.553383
192         192   966  Alex Oxlade-Chamberlain     13   238      1   0.300651
198         198  1257                  Alisson     33  2970      1   0.107682
204         204  1688         Andrew Robertson     38  3391      1   1.437934
226         226  6665             Curtis Jones     24  1174      1   1.758893
251         251  8228       Nathaniel Phillips     17  1451      1   1.027709
272         272   484             Divock Origi      9   176      0   1.081121
274         274   489             James Milner     26  1037      0   0.356574
278         278   527                   Adrián      3   270      0   0.000000
330         330   888          Xherdan Shaqiri     14   534      0   0.424721
335         335   987             Joseph Gomez      7   594      0   0.000000
375         375  3420                  Fabinho     30  2563      0   0.362489
384         384  5247               Naby Keita     10   525      0   0.393259
436         436  7376               Ozan Kabak      9   807      0   0.086028
453         453  7904        Caoimhin Kelleher      2   180      0   0.000000
465         465  8204            Neco Williams      6   252      0   0.086225
487         487  8852    Konstantinos Tsimikas      2     4      0   0.000000
498         498  9086            Rhys Williams      9   661      0   0.553240

     assists        xA  shots  key_passes  yellow_cards  red_cards position  \
1          5  6.528526    126          55             0          0    F M S
16         7  7.787755     94          61             3          0    F M S
26         7  6.116863     83          44             2          0    F M S
30         0  1.762521     46          12             2          0    F M S
116        0  1.662922     31          21             1          0      M S
130        7  8.576368     55          77             2          0      D S
161        0  2.554922     22          30             4          0      M S
162        2  1.180275      5           3             2          0      D S
172        1  1.483709     14          14             0          0    D M S
187        0  0.000000      4           0             1          0        D
192        1  0.301778      8           2             0          0    F M S
198        0  0.000000      1           0             1          0       GK
204        7  7.220492     19          65             2          0        D
226        2  1.521144     19          12             2          0      M S
251        1  0.916557     15           7             2          0      D S
272        0  0.140035      7           2             0          0      F S
274        1  0.790560     12          13             3          0    D M S
278        0  0.000000      0           0             0          0       GK
330        2  2.510420     11          19             2          0    F M S
335        0  0.065429      0           1             0          0      D S
375        0  0.298062     10           4             6          0    D M S
384        0  0.912951      9           6             1          0      M S
436        0  0.029387      1           1             3          0        D
453        0  0.000000      0           0             0          0       GK
465        0  0.193399      2           3             1          0      D S
487        0  0.000000      0           0             0          0        S
498        0  0.222205      7           2             0          0      D S

    team_title  npg       npxG    xGChain  xGBuildup
1    Liverpool   16  15.683834  28.968234   9.800236
16   Liverpool   11  14.828548  24.998923   6.057656
26   Liverpool    9  12.860213  25.271458  10.198550
30   Liverpool    9   7.057721  10.972975   4.076096
116  Liverpool    2   2.817427  13.922182  10.476277
130  Liverpool    2   2.593060  23.107881  17.648908
161  Liverpool    1   1.211306  11.152549   9.468282
162  Liverpool    1   0.784475   4.383128   4.383128
172  Liverpool    1   1.135798  11.494361  10.461348
187  Liverpool    1   0.553383   1.409594   1.288435
192  Liverpool    1   0.300651   0.998663   0.766685
198  Liverpool    1   0.107682   3.559325   3.559325
204  Liverpool    1   1.437934  19.869482  15.435009
226  Liverpool    1   1.758893   7.742866   5.182874
251  Liverpool    1   1.027709   4.325661   4.156065
272  Liverpool    0   1.081121   1.496935   0.782366
274  Liverpool    0   0.356574   5.685045   4.885257
278  Liverpool    0   0.000000   0.397439   0.397439
330  Liverpool    0   0.424721   4.585736   2.122926
335  Liverpool    0   0.000000   2.085420   2.019991
375  Liverpool    0   0.362489  11.808026  11.555005
384  Liverpool    0   0.393259   3.590221   2.329714
436  Liverpool    0   0.086028   1.863912   1.863912
453  Liverpool    0   0.000000   0.447927   0.447927
465  Liverpool    0   0.086225   1.074642   0.795018
487  Liverpool    0   0.000000   0.000000   0.000000
498  Liverpool    0   0.553240   2.306016   2.187170

8.

In [29]:
print("Pemain Arsenal:")
print(df[df['team_title'] == 'Arsenal'])

Pemain Arsenal:
     Unnamed: 0    id                player_name  games  time  goals  \
9             9  3277        Alexandre Lacazette     30  1928     13
19           19   318  Pierre-Emerick Aubameyang     28  2254     10
36           36  5656               Nicolas Pepe     28  1512      8
65           65  7322                Bukayo Saka     31  2561      5
140         140  5613                    Gabriel     22  1904      2
146         146  6482              Eddie Nketiah     17   405      2
149         149  7230           Emile Smith-Rowe     19  1382      2
152         152  7752         Gabriel Martinelli     13   577      2
160         160   204               Granit Xhaka     30  2447      1
164         164   492            Héctor Bellerín     25  2098      1
165         165   496             Mohamed Elneny     23  1540      1
180         180   700                    Willian     25  1413      1
203         203  1676                 David Luiz     20  1410      1
209         209  2517            Martin Odegaard     13   779      1
248         248  8089             Kieran Tierney     26  2215      1
267         267   181                 Bernd Leno     34  3046      0
269         269   342             Sead Kolasinac      1    90      0
275         275   508             Calum Chambers      9   660      0
322         322   847              Cédric Soares     10   746      0
348         348  1699           Shkodran Mustafi      3    43      0
354         354  1749                Rob Holding     29  2458      0
366         366  2328              Thomas Partey     23  1453      0
369         369  2446              Dani Ceballos     25  1613      0
412         412  6492               Reiss Nelson      2    59      0
423         423  6875       Rúnar Alex Rúnarsson      1    11      0
473         473  8380                 Pablo Marí     10   900      0

            xG  assists        xA  shots  key_passes  yellow_cards  red_cards  \
9    12.028909        2  2.209213     45          22             3          0
19   10.194089        3  2.352407     55          19             2          0
36    5.811174        1  1.012160     43          11             1          1
65    7.169174        3  4.511791     61          38             1          0
140   1.550638        0  0.056096     15           2             2          1
146   2.022099        1  0.742355     12           8             0          0
149   1.592160        4  3.449014     13          23             0          0
152   3.252450        1  1.745651     20           9             0          0
160   0.711673        2  1.334161     18          14             7          1
164   0.860230        2  2.171512     15          21             8          0
165   0.475616        0  0.256942      9           4             3          0
180   1.834948        5  3.591710     20          32             0          0
203   0.669567        0  0.524025     15           2             1          1
209   0.572077        1  1.678805     13          16             0          0
248   0.386677        3  3.823889     15          31             4          0
267   0.000000        0  0.000000      0           0             0          1
269   0.000000        0  0.000000      0           0             0          0
275   0.363973        1  0.960840      8           9             0          0
322   0.203543        1  0.892805      7           6             1          0
348   0.000000        0  0.000000      0           0             0          0
354   0.733921        1  0.200683     14           4             2          0
366   0.957124        2  1.121045     22          12             5          0
369   0.659258        3  2.578972     13          27             4          0
412   0.056917        0  0.000000      1           0             0          0
423   0.000000        0  0.000000      0           0             0          0
473   0.040523        0  0.054244      2           1             2          0

    position team_title  npg      npxG    xGChain  xGBuildup
9      F M S    Arsenal   10  9.745403  14.361542   2.937941
19     F M S    Arsenal    8  8.671751  14.778998   3.955129
36     F M S    Arsenal    7  5.050005   9.170708   4.217726
65   D F M S    Arsenal    5  7.169174  18.292466   9.180440
140      D S    Arsenal    2  1.550638   5.588361   5.573927
146      F S    Arsenal    2  2.022099   2.077280   0.220550
149      M S    Arsenal    2  1.592160   9.202460   5.454993
152    F M S    Arsenal    2  3.252450   6.159720   1.756597
160    D M S    Arsenal    1  0.711673  13.537367  12.521644
164      D S    Arsenal    1  0.860230   8.059892   6.266996
165      M S    Arsenal    1  0.475616   5.195761   4.651168
180    F M S    Arsenal    1  1.834948   7.110169   3.815575
203      D S    Arsenal    1  0.669567   4.749539   4.629008
209      M S    Arsenal    1  0.572077   5.008195   4.034761
248      D S    Arsenal    1  0.386677   8.525313   5.497776
267       GK    Arsenal    0  0.000000   4.290661   4.290661
269        D    Arsenal    0  0.000000   0.429358   0.429358
275      D S    Arsenal    0  0.363973   3.650803   2.707076
322      D S    Arsenal    0  0.203543   3.335598   2.919357
348        S    Arsenal    0  0.000000   0.064725   0.064725
354      D S    Arsenal    0  0.733921   7.343422   7.103263
366      M S    Arsenal    0  0.957124   7.060513   5.659220
369      M S    Arsenal    0  0.659258   9.275826   8.116633
412        S    Arsenal    0  0.056917   0.348040   0.291123
423        S    Arsenal    0  0.000000   0.000000   0.000000
473        D    Arsenal    0  0.040523   3.604975   3.590738

9.

In [30]:
print("10 pemain dengan kartu kuning terbanyak:")
print(df[['player_name', 'yellow_cards']].sort_values(by='yellow_cards', ascending=False).head(10))

10 pemain dengan kartu kuning terbanyak:
               player_name  yellow_cards
106            John McGinn            12
157        Conor Gallagher            11
125          Harry Maguire            11
259        Kalvin Phillips            10
110  Pierre-Emile Højbjerg             9
216       Luka Milivojevic             8
397           Isaac Hayden             8
218          Yves Bissouma             8
448         John Lundstram             8
399           Douglas Luiz             8

10.

In [31]:
print("10 pemain dengan kartu merah terbanyak:")
print(df[['player_name', 'red_cards']].sort_values(by='red_cards', ascending=False).head(10))

10 pemain dengan kartu merah terbanyak:
             player_name  red_cards
61            Lewis Dunk          2
488         Matthew Cash          1
493     Antonee Robinson          1
21     Christian Benteke          1
18       Matheus Pereira          1
476  Alexandre Jankewitz          1
25          Tomas Soucek          1
443            John Egan          1
433            Ben White          1
421         Matt Doherty          1